[wip: 進捗報告と今後の学習方針についての相談]
kei615ykhm/next.js13-tailwindcss-udemy-blog pull request #14
Opened 2024-08-12 07:34 UTC by kei615ykhm

## 概要

このプルリクエストは**マージを目的としていない**ため、セッション終了後は`close pull request`する予定です。

今週は、[【Next.js13】最新バージョンの Next.js13 をマイクロブログ構築しながら基礎と本質を学ぶ講座](https://www.udemy.com/course/nextjs13_learning_with_microblog)に沿って、`section4`まで進み、`App Router`の基本的なページルーティングと画像`API`の使い方、`TailwindCSS`を用いたレイアウト構築を学びました。
途中でエラーの誤解による脱線がありましたが、その後、問題を解決し予定通りに進行しています。この教材は次のスプリントで完了させる予定です。

今回のレビューでは、作業内容よりも、コミットメッセージについてや、今後の学習方針に重点をおいてご意見をいただければ幸いです。

## 学習内容

### 学んだこと

- **環境構築**: `create-next-app`の適切なセットアップ手順と各設定ファイルの役割
- **ページルーティング**: `src/app`配下の静的ルーティング設定の基本
- **コンポーネント実装**: `layout`ファイルで共通コンポーネント作成
- **API の使用**: `lorem picsum`が提供する画像`API`をブログに適用
- **TailwindCSS**: ブログの記事投稿一覧の作成を通して`TailwindCSS`のレイアウト構築
- **知識として**: `SSG`と`SSR`と`ISR`の違い、`Next.js`の`12`と`13`の違いを確認
- **エラー対処**: 出力されたログをしっかり読むことの重要性と、冷静に対処すべき理由

### 課題と反省点

- `React`の要素について触れる場面があまりなく、`Next.js`の表面的な部分しか理解できなかったこと
- コミットメッセージの運用が不適切だと感じたこと
- 実践的にコードをもっとたくさん書いて教材を進めるべきだったこと
- 確認不足が膨大な時間ロスに繋がるという自覚が足りなかったこと

マージ先のミスで作業履歴を一部ロスト: #8 
上記のミスの影響で`develop`へのマージに影響: #13 

## 相談内容

### 1. 課題と反省点について

- コミットメッセージの運用が不適切だと感じたこと
  関連情報:
  Issue: #7
  PR: #8 
  commit: 51cdc2f ~ 963c969

![スクリーンショット (372)](https://github.com/user-attachments/assets/87b93f57-6b34-4e1b-afde-f1899476c2a2)

以前、こちらの画像にある警告を見て、`Headers`という名前が競合（実際には名前衝突）していると勘違いしました。`lib.dom.d.ts`ファイルの`Headers`に関する警告が、`layout.tsx`内の`Header`と重複しているように見えたためです。さらに、`import`を記述した時のコミット履歴を残さず作業を進めた結果、発生したエラーの前後関係がわからなくなり、名前衝突だと思い込んでしまいました。

この問題は解決しましたが、エラーを誤解した背景には、コミットメッセージの管理が不十分だったことも影響しています。根本的な原因は`lib.dom.d.ts`ファイルの`Headers`が`WebAPI`の一部でコンポーネントとは無関係という知識の不足と、エラー文を正しく読まなかった私にありますが、履歴の残し方も勘違いを助長した一因でした。

このような状況で、今後同じような誤解を防ぐためにはどのような対策を取るべきでしょうか？また、コミットメッセージを適切に管理するためのコツなどのご意見をいただきたいです。

### 2. 今後の学習方針について

次のスプリントでは、進行中の教材を最後まで進める予定です。技術内容的には、`json-sever`を使ったモックデータ構築、`ISR`で取得`API`を作る、`Supabase`でデータベースを扱うなど、ブログサイトをひととおり動く形で作ります。

ですが、この教材ではデプロイがなかったことと、`React`について触れる機会が少なかったこと、実務に通用するようなレベルになるように、より踏み込んだ学習がしたいなどの理由で以下の教材を検討しています。

1. [Next.js × shadcn/ui × Supabase で本格的な Web アプリ開発を学ぶフルスタック講座](https://www.udemy.com/course/nextjs-shadcn-fullstack-webapp-dev)

選択理由: 現在学んでいる`App Router`基礎を活かしつつさらに踏み込める、`Vercel`へのデプロイがある、`React`の状態管理を実践的に触れられる、`shadcn/ui`が少し気になっていたため（`Zenn`の記事で見ていて）

2.[【フォーム開発実践】認証やお問い合わせフォームを Next.js/RHF/zod 等のモダン技術を使って開発する実践講座](https://www.udemy.com/course/form-dev-with-nextjs-rhf-zod)

選択理由: フォーム作成は基礎にして応用という以前のアドバイスから、実際に触ってみたいと考えたため

## 最後に

この進捗報告と学習計画について、フィードバックをいただければ幸いです。今後の教材選びについては「実務ができるレベルの基礎的なスキル」という観点でも、アドバイスをいただけると大変助かります。

1. コミットメッセージの改善方法や、効果的な`Git`の使い方について
2. 選択した学習教材や方針が、実務レベルの基礎スキル獲得に効果的かどうか
3. 実務で重要とされる基礎的な概念や技術があれば、それらについてのご指摘
4. 実務により近い形で学習を進めるための具体的なアドバイス

先日ご指摘いただいた、実務レベルには程遠いというお話から、自分なりに考えて今後についても掘り下げてみました。
もし、現在の学習ペースや内容に関して、改善すべき点が他にもあればぜひお聞かせください。
よろしくお願いいたします！

2024-08-12 08:22 UTC, niaka3dayo requested changes
ここまでの変更をレビューしました

2024-08-12 08:22 UTC, niaka3dayo commented on src/app/articles/new/page.tsx
> +      </form>
[MAY] フォームが設置されいますが、フォームに`action`も`onSubmit`も設置されておらず、ハンドラも存在しないため、このフォームが捜査員された場合は画面が更新されるのみだと思います。もし、後から機能を追加する必要がある場合はTODOコメントなどを残しておいたほうが良いです。

2024-08-12 08:22 UTC, niaka3dayo commented on src/app/components/ArticleList.tsx
> +        <div className="bg-white flex flex-col  justify-start p-6">
[SHOULD] 半角スペースが連続で2回入力されてしまっている個所がありますので整形したほうがいいです

2024-08-12 08:22 UTC, niaka3dayo commented on src/app/components/ArticleList.tsx
> +        <div className="bg-white flex flex-col  justify-start p-6">
[SHOULD] 半角スペースが連続で2回入力されてしまっている個所がありますので整形したほうがいいです

2024-08-12 08:22 UTC, niaka3dayo commented on src/app/Header.tsx
> +    <header className="py-5 px-10 border-b flex justify-between item-cen">
[ASK] `item-cen`というTailwindクラスを初めて見たのですが、独自定義または`items-center`の誤植でしょうか？

2024-08-12 08:33 UTC, niaka3dayo commented
質問にお答えします

## 1.コミットメッセージの改善方法や、効果的なGitの使い方について

コミットメッセージの改善については思想や価値観によっても左右されますが基本的には頻繁に打つことが大事です。
1行変更しただけでもコミットをしていいと思いますが、コミット＝作業単位です。
また、コミットメッセージは1行目にコミットの簡易的な説明、3行目以降に詳細を書くことで細かい内容を残せます。
大きな変更を1コミットで行う場合には3行目以降も書くことが大事です。


## 2.選択した学習教材や方針が、実務レベルの基礎スキル獲得に効果的かどうか

選択した教材は実務でも使えるような内容の基礎になると思いますが、本質的には実務ではほかにも様々な要件に対応しなければならないため、教材での勉強だけでは不足になると思います。
普段から新しい情報のキャッチアップをする能力や、自分で何かを作る、解決するということに慣れていくことが大事だと思います。また、AIに頼るだけでなく、Google検索で似たケースを探したり、GitHubでIssueをたどってエラーを解決するなどの能力も大切ですよ。

## 3.実務で重要とされる基礎的な概念や技術があれば、それらについてのご指摘

実務で大事な概念はこの場合はフォーム部分とセキュリティの扱いだと思います。
`Next.js`はフルスタックフレームワークですが、実際にフォームで送信された内容がどのようにサーバーで処理されるのか、どのタイミングでメールを送るのか、またそれはどういう風にセキュリティを担保するのか、などの要件をしっかりと設計することが実務では大事です。

また、ISR・SSR・SSGはサーバーの運用コストなども計算してしっかりとどれを使うか要件ごとに定める必要があります。
たとえば、ブログサイトなどの場合は、VercelのWebhook機能などを利用してCMSでの更新時に全てSSGでビルドしなおすなどのやり方もよく使われます。

## 4. 実務により近い形で学習を進めるための具体的なアドバイス

OSS（オープンソース）開発に参加したり、複数人でのGitプロジェクトに参加する経験を積めると一番いいと思います。
一人で学習することには限界があるので、自分の知識が正しいかどうかの検証が常に必要になります。
コーディングにおいては他人のコードやコミットメッセージを見ることも大事です。

2024-08-12 08:36 UTC, niaka3dayo commented
@kei615ykhm レビューと質問への回答を完了しました

2024-08-12 08:38 UTC, kei615ykhm commented on src/app/Header.tsx
> +    <header className="py-5 px-10 border-b flex justify-between item-cen">
ソースコードと公式ドキュメントを確認しました。
申し訳ございません。私の誤植でした。早急に修正いたします。

2024-08-12 08:45 UTC, kei615ykhm commented on src/app/articles/new/page.tsx
> +      </form>
udemyの教材とソースコードを確認しましたところ、教材の`section4`では「あとで追加する」と説明があり、ソースには記述がありました。
しかし、ご指摘の通りコメントを残すべきでした。

2024-08-12 08:47 UTC, kei615ykhm commented on src/app/components/ArticleList.tsx
> +        <div className="bg-white flex flex-col  justify-start p-6">
ご指摘ありがとうございます。早急に修正いたします。

2024-08-12 10:04 UTC, kei615ykhm commented
詳細なアドバイス、ありがとうございます。

いただいたフィードバックをもとに、今後の学習方法やスキル向上に取り組んでいきたいと思います。以下に、各ポイントに対する私の考えと次のステップについてまとめました。

### 1. コミットメッセージの改善と効果的なGitの使い方

「大きな変更を1コミットで…」という点について考えました。これまでの私は、作業の大小に関わらずコメントを残せば良いと考えていましたが、今回のフィードバックを受け、それがかえってコミットメッセージを分かりにくくしてしまう原因だったかもしれないと気づきました。

今後は、アドバイスを参考に、簡潔で明確に伝わるコミットメッセージを心がけていきます。

### 2. 実務レベルの基礎スキル習得について

「実務は教材通りにはいかない」ということを、`Next.js`の学習を通じて実感しています。`Zenn`や`connpass`での勉強会や技術カンファレンスに参加して情報収集をしていますが、やはり「教材に頼らずに何かを作る」経験が重要だと感じています。

また、「自分がやったことは誰かがすでにやっている」というアドバイスに基づき、今後はGitHubで他の人のコードをより意識して確認し、学びを深めていきます。

### 3. 実務で重要な基礎概念や技術について

フィードバックをいただいた内容について、現状では知識としては理解しているものの、実際に触れていないため、実感としてはまだ掴めていない部分があります。

今後の学習でバックエンド部分にも触れる予定ですので、まずはそれらを実際に経験し、理解を深めていきます。いただいた内容を意識しながら、学習に取り組んでいきます。

### 4. 実務に近い形での学習進行について

現状、基礎学習で手一杯なところがあり、OSS開発や複数人でのプロジェクトに参加するにはまだ余裕がありません。しかし、ひとりでの学習には限界があると感じており、現在はコードリーディングや`connpass`での勉強会に参加することで知識を広げています。

今後は「機会があれば」ではなく、「自ら機会を作る」ことを意識して行動していきます。

## 最後に

`action`や`onSubmit`の設置、データベースを意識したセキュリティの扱いなどは、今後の学習でカバーする予定ですので、現段階ではまだ対応が難しいと感じています。しかし、コメントを残すことや、コミットメッセージの件など、日ごろの意識を変えることはすぐにでも始められると感じています。

今回いただいたアドバイスをもとに、まずはできることから着実に進めていきます。貴重なお時間をいただき、ありがとうございました！

2024-08-15 09:13 UTC, kei615ykhm commented
フィードバックいただいた内容に沿って、問題点をすべて修正しました。
このPRはマージを目的としたものではないため、クローズします。

2024-08-15 09:14 UTC, closed without merging